### ISSUE TITLE
终于有人做ba主题了，非常感谢，请教一点使用上的问题)

### ISSUE THREAD

**Issue by yoyos12138** [Machillka/GameDevClub-GRUB-Theme#1]
请教一下大佬这个有考虑直接弄成解压版那种然后我直接手动指定改配置文件 然后update那种那种方法么（就像大多数主题一样）

**Comment by Machillka** [comment]
收到意见！后面写个脚本制定修改组件。请问您觉得有什么组件是需要修改的呢？（比如壁纸？字体？

**Comment by yoyos12138** [comment]
> 收到意见！后面写个脚本制定修改组件。请问您觉得有什么组件是需要修改的呢？（比如壁纸？字体？

其实是安装方式（我比较喜欢自己解压和修改grub配置文件自己执行update-grub指令，不太喜欢执行别人的脚本）(虽然不怎么玩ba但是确实很喜欢ba的美术画风) 大佬有没有什么交流群什么的东西啊

**Comment by yoyos12138** [comment]
> > 收到意见！后面写个脚本制定修改组件。请问您觉得有什么组件是需要修改的呢？（比如壁纸？字体？
> 
> 其实是安装方式（我比较喜欢自己解压和修改grub配置文件自己执行update-grub指令，不太喜欢执行别人的脚本）(虽然不怎么玩ba但是确实很喜欢ba的美术画风) 大佬有没有什么交流群什么的东西啊

想给大佬打点米

**Comment by yoyos12138** [comment]
那个爱发电怎么是未认证（

**Comment by Machillka** [comment]
我在release里面上传了zip文件，可以下载完然后mv过去，也可以在zip里面自己修改文件。如果还有什么问题可以继续提issue！

**Comment by Machillka** [comment]
害，自身水平不够，还没有比较好交流群，不过可以现在一起建一个 [doge]

**Comment by Machillka** [comment]
在个人首页添加了支付方式！非常感谢您的支持
